name: Format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: astral-sh/ruff-action@v4.0.0
        id: lint
        continue-on-error: true
        with:
          args: "check"
      - name: Format
        uses: astral-sh/ruff-action@v4.0.0
        id: format
        continue-on-error: true
        with:
          args: "format --diff"
      - name: Fail if any check failed
        if: steps.lint.outcome == 'failure' || steps.format.outcome == 'failure'
        run: exit 1
